using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
namespace EduAssist.API.Services;
public class AIService : IAIService
{
    private readonly IConfiguration _configuration;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<AIService> _logger;
    public AIService(IConfiguration configuration, IHttpClientFactory httpClientFactory, ILogger<AIService> logger)
    { _configuration = configuration; _httpClientFactory = httpClientFactory; _logger = logger; }

    public async Task<string> GenerateResponseAsync(string query, string categoryName, string preferredLanguage)
    {
        var apiKey = _configuration["OpenAI:ApiKey"];
        if (string.IsNullOrEmpty(apiKey))
        {
            _logger.LogWarning("OpenAI API key not configured. Using mock response.");
            await Task.Delay(500);
            return GenerateMockResponse(query, categoryName, preferredLanguage);
        }
        try
        {
            var client = _httpClientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);
            var body = new { model = _configuration["OpenAI:Model"] ?? "gpt-3.5-turbo", messages = new[] { new { role = "system", content = $"You are EduAssist, an AI education assistant. Category: {categoryName}. Language: {preferredLanguage}. Provide clear educational responses." }, new { role = "user", content = query } }, max_tokens = 1500, temperature = 0.7 };
            var response = await client.PostAsync("https://api.openai.com/v1/chat/completions", new StringContent(JsonSerializer.Serialize(body), Encoding.UTF8, "application/json"));
            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync();
                using var doc = JsonDocument.Parse(json);
                return doc.RootElement.GetProperty("choices")[0].GetProperty("message").GetProperty("content").GetString() ?? "No response.";
            }
            throw new Exception($"OpenAI error: {response.StatusCode}");
        }
        catch (Exception ex) { _logger.LogError(ex, "AI generation failed"); throw; }
    }

    private static string GenerateMockResponse(string query, string categoryName, string preferredLanguage) =>
        $"## {categoryName} - AI Response\n\n**Question:** {query}\n\n### Explanation:\nThis is a mock AI response for the **{categoryName}** category. Configure your OpenAI API key in appsettings.json for real AI responses.\n\n### Key Points:\n1. Topic: {categoryName}\n2. Language: {preferredLanguage}\n3. Your question has been saved for review\n\n*Generated by EduAssist AI*";
}
